name: antonio_m5a1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/person1.jpg
  - assets/person2.jpg
  - assets/person3.jpg
  - assets/backpack.jpg
  - assets/electric_fan.jpg
  - assets/guitar.jpg
  - assets/sofa.jpg
